name: Deploy Quizlam Game

on:
  repository_dispatch:
    types: [trigger-deployment]  # Listens for this event type

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo (deployment scripts)
        uses: actions/checkout@v3

      - name: Checkout game repo code
        uses: actions/checkout@v3
        with:
          repository: FarazAleemWork/devJeo
          token: ${{ secrets.CICD_DEPLOY_PAT }}   # Same PAT secret
          path: devJeo

      - name: Copy files to Azure VM and restart app
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: jeopardydevuser
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          source: "devJeo/quizlambd devJeo/quizlamfd"
          target: "~/devJeo"

      - name: SSH to Azure VM and restart app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: jeopardydevuser
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          script: |
            cd ~/devJeo
            pm2 restart quizlam || pm2 start quizlambd/server/server.js --name quizlam

